apiVersion: v1
kind: Service
metadata:
  name: school-app-service
  namespace: school-management
  labels:
    app: school-app
spec:
  type: ClusterIP
  selector:
    app: school-app
  ports:
    - name: fastcgi
      port: 80
      targetPort: fastcgi
      protocol: TCP
  sessionAffinity: None
