apiVersion: v1
kind: Service
metadata:
  name: school-redis
  namespace: school-management
  labels:
    app: school-redis
spec:
  type: ClusterIP
  selector:
    app: school-redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
