apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    app: grafana
    project: school-management
type: Opaque
stringData:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 30s

  loki.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki:3100
        editable: false
        jsonData:
          maxLines: 1000
