apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: grafana
namespace: monitoring
resources:
  - grafana-deployment.yaml
  - grafana-service.yaml
  - grafana-configmap.yaml
  - grafana-datasources.yaml
  - grafana-dashboard-provider-configmap.yaml

configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/school-k8s-monitoring.json

generatorOptions:
  disableNameSuffixHash: true
