apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-production

namespace: monitoring

resources:
  - ../../base

commonLabels:
  environment: production

patches:
  # Prometheus resource limits & replicas
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: prometheus-monitoring
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 100m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi

  # Grafana resource limits & replicas
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: grafana
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  # Loki resource limits & replicas
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: loki
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 50m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 128Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 256Mi

  # Prometheus storage
  - target:
      group: v1
      kind: PersistentVolumeClaim
      name: prometheus-storage-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi

  # Grafana storage
  - target:
      group: v1
      kind: PersistentVolumeClaim
      name: grafana-storage-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 1Gi

  # Loki storage
  - target:
      group: v1
      kind: PersistentVolumeClaim
      name: loki-storage-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 5Gi

  # Prometheus Service NodePort
  - target:
      version: v1
      kind: Service
      name: prometheus
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30192

  # Grafana Service NodePort
  - target:
      version: v1
      kind: Service
      name: grafana
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30546
